# -*- coding: utf-8 -*-
"""Injection file

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRCMcGf6pveSx-IlB1hhRkDB1VQ8ay9H
"""

# -*- coding: utf-8 -*-
"""Injection file

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRCMcGf6pveSx-IlB1hhRkDB1VQ8ay9H
"""

import random
import numpy as np
import os
import shutil
import scipy.signal

# Define the range of parameters
#m1,m2,lensed_ra,lensed_dec,lens mass   = 5 parameters
#source_ra=0,source_dec=0



min_value = [5, 5, 0, 0, 1e9]
max_value = [100, 100, 4, np.pi /45,  2, 1e16]
# Create a function to generate a list of 5 parameters
def generate_parameters():
  # Create an empty list to store the parameters
  parameters = []
  # Iterate over the range of parameters
  for i in range(5):
    # Generate a random value within the range
    value = random.uniform(min_value[i], max_value[i])
    # Add the value to the list of parameters
    parameters.append(value)
  # Return the list of parameters
  return parameters
# Generate 5000 lists of 5 parameters
parameters_list = []
for i in range(5000):
  parameters = generate_parameters()
  parameters_list.append(parameters)

import os
drive_location = '/content/sample_data'
if not os.path.exists(drive_location):
    os.makedirs(drive_location)

save_file = os.path.join(drive_location, 'parameters.npy')
np.save(save_file, parameters_list)
print(f"Saved {len(parameters_list)} parameter lists to {save_file}")

import os
if not os.path.exists(drive_location):
    os.makedirs(drive_location)
# Check if the file exists
if os.path.isfile(os.path.join(drive_location, 'parameters.npy')):
    # Load the saved file
    saved_parameters = np.load(os.path.join(drive_location, 'parameters.npy'), allow_pickle=True)
    # Check if the loaded data is of type numpy.ndarray
    if isinstance(saved_parameters, np.ndarray):
        print("The file parameters.npy exists and is in numpy format.")
    else:
        print("The file parameters.npy exists but is not in numpy format.")
else:
    print("The file parameters.npy does not exist.")

import google.colab
google.colab.drive.mount('/content/drive')
drive_location = '/content/drive/MyDrive/parameters.npy'
np.save(drive_location, parameters_list)