# -*- coding: utf-8 -*-
"""Trimmings_shashwatsir.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGRODDFQwKa8cbyu9oIL_wfNLBXnLOuw
"""

from google.colab import drive
drive.mount('/content/drive')
!ls "/content/drive/MyDrive/waveform"

# saves both trimmed and already desirable sized waveforms to trimmed_waveforms_1
import os
import numpy as np

desired_size = 614
waveform_folder = '/content/drive/MyDrive/waveform/waveform'
trimmed_waveform_1_folder = '/content/drive/MyDrive/trimmed_waveform_1'

if not os.path.exists(trimmed_waveform_1_folder):
    os.makedirs(trimmed_waveform_1_folder)

for file_name in os.listdir(waveform_folder):
    file_path = os.path.join(waveform_folder, file_name)
    if file_name.endswith('.npy'):
        array = np.load(file_path)
        print(f"Loaded array from {file_path} with shape {array.shape} and size {array.size}")
        if array.size > desired_size: #size greater than desired
            trimmed_array = array[:desired_size]
            np.save(os.path.join(trimmed_waveform_1_folder, file_name), trimmed_array)
            print(f"Saved trimmed array to {os.path.join(trimmed_waveform_1_folder, file_name)} with shape {trimmed_array.shape} and size {trimmed_array.size}")
        else: # size equal to or less than desired
            print(f"Array from {file_path} has size {array.size} and does not need to be trimmed")
            # Save the array to the trimmed_waveform folder even if it doesn't need to be trimmed
            np.save(os.path.join(trimmed_waveform_1_folder, file_name), array)
    else:
       print(f"File {file_name} is not an .npy file and does not need to be trimmed")

#checks the number of file in the folder
import os

trimmed_waveform_folder = '/content/drive/MyDrive/trimmed_waveform_1'

npy_files = [f for f in os.listdir(trimmed_waveform_1_folder) if f.endswith('.npy')]

print(f'Number of .npy files in {trimmed_waveform_1_folder}: {len(npy_files)}')

# checking size of all of the trimmed waveforms
import os

trimmed_waveform_1_folder = '/content/drive/MyDrive/trimmed_waveform_1'

for file_name in os.listdir(trimmed_waveform_1_folder):
    file_path = os.path.join(trimmed_waveform_1_folder, file_name)
    if os.path.isfile(file_path):
        file_size = os.path.getsize(file_path)
        print(f"File {file_path} has size {file_size} bytes")

import os
import zipfile

trimmed_waveform_folder = '/content/drive/MyDrive/trimmed_waveform_1'
zip_filename = 'trimmed_waveform_1.zip'

with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(trimmed_waveform_folder):
        for file in files:
            file_path = os.path.join(root, file)
            zipf.write(file_path)

print(f'Successfully created zip file {zip_filename}')

# this code only saves half of the files that is 7514
import os
import numpy as np

desired_size = 614
waveform_folder = '/content/drive/MyDrive/waveform/waveform'
trimmed_waveform_folder = '/content/drive/MyDrive/trimmed_waveform'

if not os.path.exists(trimmed_waveform_folder):
    os.makedirs(trimmed_waveform_folder)

for file_name in os.listdir(waveform_folder):
    file_path = os.path.join(waveform_folder, file_name)
    if file_name.endswith('.npy'):
        array = np.load(file_path)
        print(f"Loaded array from {file_path} with shape {array.shape} and size {array.size}")
        if array.size > desired_size:
            trimmed_array = array[:desired_size]
            np.save(os.path.join(trimmed_waveform_folder, file_name), trimmed_array)
            print(f"Saved trimmed array to {os.path.join(trimmed_waveform_folder, file_name)} with shape {trimmed_array.shape} and size {trimmed_array.size}")
        else:
            print(f"Array from {file_path} has size {array.size} and does not need to be trimmed")
    else:
       print(f"File {file_name} is not an .npy file and does not need to be trimmed")

# the code for saving only trimmed waveforms in a folder
import os
import numpy as np

desired_size = 614
waveform_folder = '/content/drive/MyDrive/waveform/waveform'
trimmed_waveform_folder = '/content/drive/MyDrive/trimmed_waveform'

if not os.path.exists(trimmed_waveform_folder):
    os.makedirs(trimmed_waveform_folder)

for file_name in os.listdir(waveform_folder):
    file_path = os.path.join(waveform_folder, file_name)
    if file_name.endswith('.npy'):
        array = np.load(file_path)
        print(f"Loaded array from {file_path} with shape {array.shape} and size {array.size}")
        if array.size > desired_size:
            trimmed_array = array[:desired_size]
            np.save(os.path.join(trimmed_waveform_folder, file_name), trimmed_array)
            print(f"Saved trimmed array to {os.path.join(trimmed_waveform_folder, file_name)} with shape {trimmed_array.shape} and size {trimmed_array.size}")