# -*- coding: utf-8 -*-
"""Unlensed waveforms

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1viq9Hbi_zObC3msfZvKgeYse-WawP3v8
"""

import sys
!{sys.executable} -m pip install pycbc ligo-common emcee==2.2.1 --no-cache-dir



# Commented out IPython magic to ensure Python compatibility.
# %%shell
# git clone https://github.com/SSingh087/lensotronomy-1.7.0.git
# cd lensotronomy-1.7.0/
# python setup.py install
# cd ..
# git clone https://github.com/SSingh087/lensGW.git
# cd lensGW
# python setup.py install
# cd ..
# git clone https://github.com/SSingh087/lensGW-PyCBC-plugin.git
# cd lensGW-PyCBC-plugin
# python setup.py install
# cd ..
# git clone https://github.com/SSingh087/sensitivity-curves.git

from pycbc import waveform
mass1=30
mass2=30
delta_t=1.0/218
f_lower=10
optim='False'
hp, hc = waveform.get_td_waveform(approximant='TaylorF2', mass1=mass1, mass2=mass2, delta_t=delta_t, f_lower=f_lower)
import pylab
pylab.plot(hp.sample_times, hp)